In [1]:
import numpy as np

In [2]:
# load dataset

import pandas as pd
df = pd.read_csv("global air pollution dataset.csv")

In [3]:
df.head()

Country              City  AQI Value AQI Category  CO AQI Value  \
0  Russian Federation        Praskoveya         51     Moderate             1   
1              Brazil  Presidente Dutra         41         Good             1   
2               Italy   Priolo Gargallo         66     Moderate             1   
3              Poland         Przasnysz         34         Good             1   
4              France          Punaauia         22         Good             0   

  CO AQI Category  Ozone AQI Value Ozone AQI Category  NO2 AQI Value  \
0            Good               36               Good              0   
1            Good                5               Good              1   
2            Good               39               Good              2   
3            Good               34               Good              0   
4            Good               22               Good              0   

  NO2 AQI Category  PM2.5 AQI Value PM2.5 AQI Category  
0             Good               51           Moderate  
1             Good               41               Good  
2             Good               66           Moderate  
3             Good               20               Good  
4             Good                6               Good

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23463 entries, 0 to 23462
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Country             23036 non-null  object
 1   City                23462 non-null  object
 2   AQI Value           23463 non-null  int64 
 3   AQI Category        23463 non-null  object
 4   CO AQI Value        23463 non-null  int64 
 5   CO AQI Category     23463 non-null  object
 6   Ozone AQI Value     23463 non-null  int64 
 7   Ozone AQI Category  23463 non-null  object
 8   NO2 AQI Value       23463 non-null  int64 
 9   NO2 AQI Category    23463 non-null  object
 10  PM2.5 AQI Value     23463 non-null  int64 
 11  PM2.5 AQI Category  23463 non-null  object
dtypes: int64(5), object(7)
memory usage: 2.1+ MB


In [5]:
df.shape

(23463, 12)

In [6]:
df.columns

Index(['Country', 'City', 'AQI Value', 'AQI Category', 'CO AQI Value',
       'CO AQI Category', 'Ozone AQI Value', 'Ozone AQI Category',
       'NO2 AQI Value', 'NO2 AQI Category', 'PM2.5 AQI Value',
       'PM2.5 AQI Category'],
      dtype='object')

In [7]:
df.describe()

AQI Value  CO AQI Value  Ozone AQI Value  NO2 AQI Value  \
count  23463.000000  23463.000000     23463.000000   23463.000000   
mean      72.010868      1.368367        35.193709       3.063334   
std       56.055220      1.832064        28.098723       5.254108   
min        6.000000      0.000000         0.000000       0.000000   
25%       39.000000      1.000000        21.000000       0.000000   
50%       55.000000      1.000000        31.000000       1.000000   
75%       79.000000      1.000000        40.000000       4.000000   
max      500.000000    133.000000       235.000000      91.000000   

       PM2.5 AQI Value  
count     23463.000000  
mean         68.519755  
std          54.796443  
min           0.000000  
25%          35.000000  
50%          54.000000  
75%          79.000000  
max         500.000000

In [8]:
df.isna().sum()

Country               427
City                    1
AQI Value               0
AQI Category            0
CO AQI Value            0
CO AQI Category         0
Ozone AQI Value         0
Ozone AQI Category      0
NO2 AQI Value           0
NO2 AQI Category        0
PM2.5 AQI Value         0
PM2.5 AQI Category      0
dtype: int64

In [9]:
df.drop(columns=['Country', "City"], inplace=True)
df.head()

AQI Value AQI Category  CO AQI Value CO AQI Category  Ozone AQI Value  \
0         51     Moderate             1            Good               36   
1         41         Good             1            Good                5   
2         66     Moderate             1            Good               39   
3         34         Good             1            Good               34   
4         22         Good             0            Good               22   

  Ozone AQI Category  NO2 AQI Value NO2 AQI Category  PM2.5 AQI Value  \
0               Good              0             Good               51   
1               Good              1             Good               41   
2               Good              2             Good               66   
3               Good              0             Good               20   
4               Good              0             Good                6   

  PM2.5 AQI Category  
0           Moderate  
1               Good  
2           Moderate  
3               Good  
4               Good

In [10]:
for i in df.columns:
    if np.dtype(df[i])=="O":
        print(f"{i} {len(df[i].unique())}: {df[i].unique()}")
        print("-------------")

AQI Category 6: ['Moderate' 'Good' 'Unhealthy for Sensitive Groups' 'Unhealthy'
 'Very Unhealthy' 'Hazardous']
-------------
CO AQI Category 3: ['Good' 'Unhealthy for Sensitive Groups' 'Moderate']
-------------
Ozone AQI Category 5: ['Good' 'Moderate' 'Unhealthy for Sensitive Groups' 'Unhealthy'
 'Very Unhealthy']
-------------
NO2 AQI Category 2: ['Good' 'Moderate']
-------------
PM2.5 AQI Category 6: ['Moderate' 'Good' 'Unhealthy for Sensitive Groups' 'Unhealthy'
 'Very Unhealthy' 'Hazardous']
-------------


In [11]:
from sklearn.model_selection import train_test_split

# Drop unnecessary columns
drop_column = ["AQI Value"] # Column of AQI Value is dropped cause we want to predict AQI Category from AQI value and category of pollutants
x = df.drop(drop_column, axis=1) # Features
y = df["AQI Category"] # Targer variable
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [12]:
from sklearn.preprocessing import LabelEncoder
# Encode the target variable to numeric values
# This allows compatibility with machine learning models
# Encode the target variable
category_value = ["Good", "Moderate", "Unhealthy", "Unhealthy for Sensitive Groups", "Very Unhealthy", "Hazardous"]
encoder = LabelEncoder()
y = encoder.fit_transform(y)  # Converts AQI categories to numeric labels

In [23]:
y

array([2, 0, 2, ..., 0, 2, 2])

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
# Define preprocessing for numerical and ordinal (categorical) features
# Numerical features: Impute missing values and scale
num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),  # Replace missing values with the median
    ('scaler', StandardScaler())  # Normalize the data
])

# Ordinal features: Impute missing values and encode AQI categories
ord_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),  # Replace missing values with the most frequent value
    ('encoder', OrdinalEncoder(categories=[category_value]*4))  # Encode categories into ordinal numbers
])

# Combine preprocessing steps for different feature types
preprocessor = ColumnTransformer(transformers=[
    ("num_features", num_transformer, ["CO AQI Value", "Ozone AQI Value", "NO2 AQI Value", "PM2.5 AQI Value"]),
    ("ord_features", ord_transformer, ["CO AQI Category", "Ozone AQI Category", "NO2 AQI Category", "PM2.5 AQI Category"])
])

# Apply preprocessing to the training and testing data
x_train = preprocessor.fit_transform(x_train)
x_test = preprocessor.transform(x_test)

In [14]:
# Encode the target variable for the model
target_encoder = OrdinalEncoder(categories=[category_value])
y_train_encoded = target_encoder.fit_transform(y_train.values.reshape(-1, 1)).ravel()
y_test_encoded = target_encoder.transform(y_test.values.reshape(-1, 1)).ravel()

In [20]:
y_train_encoded

array([0., 0., 1., ..., 1., 0., 0.])

In [21]:
y_test_encoded

array([1., 0., 0., ..., 2., 1., 0.])

In [16]:
from sklearn.metrics import f1_score, make_scorer
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
# Define a custom scorer to focus on the F1-score for the 'Hazardous' category
# This helps in prioritizing the model's performance for the minority class
f1_hazardous_scorer = make_scorer(f1_score, labels=[5], average=None)

# Initialize the XGBClassifier model
model = XGBClassifier(eval_metric="mlogloss", random_state=42, gamma=0)

# Define a parameter grid for hyperparameter tuning using GridSearchCV
param_grid = {
    "learning_rate": [0.05, 0.01],  # Learning rate controls the step size at each iteration
    "n_estimators": [20, 50, 100],  # Number of trees in the model
    "max_depth": [7, 9],  # Maximum depth of the trees
    "subsample": [0.6, 0.8],  # Fraction of samples to use for training each tree
    "colsample_bytree": [0.6, 0.8]  # Fraction of features to use for training each tree
}

# Perform GridSearchCV to find the best hyperparameters
# The evaluation metric focuses on the F1-score for the 'Hazardous' class
grid_search = GridSearchCV(estimator=model, param_grid=param_grid,
                           scoring=f1_hazardous_scorer, cv=5, verbose=1, n_jobs=-1)
grid_search.fit(x_train, y_train_encoded)

# Get the best model and parameters from GridSearchCV
best_model = grid_search.best_estimator_
print("Best Parameters:", grid_search.best_params_)
print("Best F1-Score for 'Hazardous':", grid_search.best_score_)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
Best Parameters: {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 7, 'n_estimators': 20, 'subsample': 0.8}
Best F1-Score for 'Hazardous': 0.9608822212270487


In [17]:
# Predict on the training data using the best model
y_train_pred = best_model.predict(x_train)

# Evaluate the model on the training data
f1_scores = f1_score(y_train_encoded, y_train_pred, average=None)
for i, category in enumerate(category_value):
    print(f"F1 score for '{category}' class: {f1_scores[i]:.4f}")

F1 score for 'Good' class: 1.0000
F1 score for 'Moderate' class: 1.0000
F1 score for 'Unhealthy' class: 1.0000
F1 score for 'Unhealthy for Sensitive Groups' class: 1.0000
F1 score for 'Very Unhealthy' class: 0.9784
F1 score for 'Hazardous' class: 0.9653


In [18]:
from sklearn.metrics import classification_report
# Predict on the test data using the best model
y_predict = best_model.predict(x_test)

# Decode predictions back to original AQI categories for better interpretability
y_predict_decoded = target_encoder.inverse_transform(y_predict.reshape(-1, 1)).ravel()
y_test_decoded = target_encoder.inverse_transform(y_test_encoded.reshape(-1, 1)).ravel()

# Evaluate the model on the test data and print a classification report
print(classification_report(y_test_decoded, y_predict_decoded))

                                precision    recall  f1-score   support

                          Good       1.00      1.00      1.00      2014
                     Hazardous       0.97      0.86      0.91        42
                      Moderate       1.00      1.00      1.00      1837
                     Unhealthy       1.00      1.00      1.00       419
Unhealthy for Sensitive Groups       1.00      1.00      1.00       321
                Very Unhealthy       0.91      0.98      0.94        60

                      accuracy                           1.00      4693
                     macro avg       0.98      0.97      0.98      4693
                  weighted avg       1.00      1.00      1.00      4693

